/**
 * MPVP — Mock Data
 * Realistic Pakistani context mock data for development.
 * This data simulates the real API responses.
 */
import type { Assignment, Inspector, AppNotification } from '@/types/api.types';
import type { FindingsSchema } from '@/types/schema.types';

// ─── Mock Inspector ───────────────────────────────────────

export const mockInspector: Inspector = {
  id: 'insp-001',
  email: 'ahmed.khan@mpvp.pk',
  full_name: 'Ahmed Raza Khan',
  cnic_number: '4210112345671',
  designation: 'senior',
  employment_type: 'full_time',
  cities_covered: ['Karachi', 'Hyderabad'],
  bank_scope: 'multi_bank',
  assigned_bank_id: null,
  is_first_login: false,
  phone_number: '+923001234567',
  profile_initials: 'AK',
};

// ─── Mock Findings Schemas ───────────────────────────────

export const mockIstisnaSchema: FindingsSchema = [
  { key: 'asset_specs', label: 'Asset Specifications', type: 'textarea', required: true, placeholder: 'Technical description, quantity, quality standards' },
  { key: 'contract_price', label: 'Total Contract Price', type: 'number', required: true, placeholder: 'Enter amount in PKR' },
  { key: 'payment_schedule', label: 'Payment Schedule', type: 'dropdown', required: true, options: ['Advance', 'Milestone', 'Deferred'] },
  { key: 'delivery_date', label: 'Delivery Date', type: 'date', required: true },
  { key: 'delivery_location', label: 'Delivery Location', type: 'text', required: true },
  { key: 'penalty_clauses', label: 'Penalty Clauses', type: 'textarea', required: false, placeholder: 'Optional delay penalties' },
  { key: 'manufacturing_timeline', label: 'Manufacturing Timeline', type: 'date_range', required: true },
  { key: 'ownership_transfer', label: 'Ownership Transfer Terms', type: 'textarea', required: true },
  { key: 'warranty_terms', label: 'Warranty / Defect Liability Terms', type: 'textarea', required: true },
];

export const mockSalamSchema: FindingsSchema = [
  { key: 'goods_description_salam', label: 'Goods Description as per Salam Agreement', type: 'textarea', required: true, placeholder: 'Detailed description of fungible goods' },
  { key: 'commodity_type', label: 'Commodity Type', type: 'text', required: true, placeholder: 'Fungible goods only' },
  { key: 'exact_quantity', label: 'Exact Quantity', type: 'number', required: true, placeholder: 'Enter weight/pieces' },
  { key: 'quantity_unit', label: 'Unit', type: 'dropdown', required: true, options: ['kg', 'ton', 'litre', 'piece'] },
  { key: 'quality_grade', label: 'Quality Grade', type: 'dropdown', required: true, options: ['Grade A', 'Grade B', 'Grade C', 'Custom'] },
  { key: 'full_contract_price', label: 'Full Contract Price', type: 'number', required: true },
  { key: 'payment_confirmation', label: 'Full Payment Confirmed', type: 'boolean', required: true, default_value: false },
  { key: 'delivery_date', label: 'Delivery Date', type: 'date', required: true },
  { key: 'delivery_location', label: 'Delivery Location', type: 'text', required: true },
  { key: 'responsibility', label: 'Storage / Transport Responsibility', type: 'dropdown', required: true, options: ['Buyer', 'Seller', 'Third Party'] },
];

export const mockMurabahaSchema: FindingsSchema = [
  { key: 'asset_details', label: 'Asset Details', type: 'textarea', required: true, placeholder: 'Description, model, serial number' },
  { key: 'purchase_cost', label: 'Original Purchase Cost', type: 'number', required: true },
  { key: 'profit_margin', label: 'Agreed Profit Margin (%)', type: 'number', required: true },
  { key: 'final_price', label: 'Final Sale Price', type: 'number', required: true, default_value: 0 },
  { key: 'payment_mode', label: 'Payment Mode', type: 'dropdown', required: true, options: ['Lump Sum', 'Installments'] },
  { key: 'late_payment_terms', label: 'Late Payment Terms', type: 'textarea', required: true, default_value: 'Includes mandatory charity clause for defaults.' },
  { key: 'ownership_proof', label: 'Asset Ownership Proof', type: 'file_upload', required: true },
];

export const mockIjarahSchema: FindingsSchema = [
  { key: 'asset_details', label: 'Asset Details', type: 'textarea', required: true },
  { key: 'lease_duration', label: 'Lease Duration (Months)', type: 'number', required: true },
  { key: 'rental_amount', label: 'Rental Amount', type: 'number', required: true },
  { key: 'payment_frequency', label: 'Payment Frequency', type: 'dropdown', required: true, options: ['Monthly', 'Quarterly', 'Annually'] },
  { key: 'maintenance_resp', label: 'Maintenance Responsibility', type: 'dropdown', required: true, options: ['Lessor', 'Lessee'] },
  { key: 'takaful_resp', label: 'Takaful (Insurance) Responsibility', type: 'dropdown', required: true, options: ['Lessor', 'Lessee'] },
  { key: 'ownership_transfer_clause', label: 'Ownership Transfer Clause', type: 'boolean', required: true, default_value: false },
  { key: 'transfer_terms', label: 'Transfer Terms', type: 'textarea', required: false },
  { key: 'security_deposit', label: 'Security Deposit', type: 'number', required: false },
];

export const mockMusharakahSchema: FindingsSchema = [
  { key: 'business_purpose', label: 'Business Purpose', type: 'textarea', required: true },
  { key: 'tenure', label: 'Tenure', type: 'date_range', required: false },
  { key: 'partners', label: 'Partners List', type: 'partner_list', required: true },
  { key: 'exit_terms', label: 'Exit Terms', type: 'textarea', required: true },
];

export const mockMudarabahSchema: FindingsSchema = [
  { key: 'capital_amount', label: 'Capital Amount', type: 'number', required: true },
  { key: 'rab_ul_maal_name', label: 'Capital Provider Name (Rab-ul-Maal)', type: 'text', required: true },
  { key: 'rab_ul_maal_id', label: 'Capital Provider ID', type: 'text', required: true },
  { key: 'mudarib_name', label: 'Manager Name (Mudarib)', type: 'text', required: true },
  { key: 'mudarib_id', label: 'Manager ID', type: 'text', required: true },
  { key: 'profit_sharing_ratio', label: 'Profit Sharing Split (%)', type: 'number', required: true, placeholder: 'Split between parties' },
  { key: 'investment_scope', label: 'Investment Scope', type: 'textarea', required: true },
  { key: 'loss_treatment', label: 'Loss Treatment', type: 'textarea', required: true, default_value: 'Borne by capital provider unless Mudarib negligence.' },
  { key: 'reporting_freq', label: 'Reporting Frequency', type: 'dropdown', required: true, options: ['Monthly', 'Quarterly', 'Bi-Annually', 'Annually'] },
  { key: 'tenure', label: 'Tenure', type: 'date_range', required: true },
  { key: 'termination_conditions', label: 'Termination Conditions', type: 'textarea', required: true },
];

export const mockSukukSchema: FindingsSchema = [
  { key: 'asset_details', label: 'Underlying Asset Details', type: 'textarea', required: true },
  { key: 'spv_structure', label: 'SPV Structure', type: 'textarea', required: true },
  { key: 'issue_size', label: 'Issue Size', type: 'number', required: true },
  { key: 'profit_rate', label: 'Profit Rate (%)', type: 'number', required: true },
  { key: 'tenure', label: 'Tenure', type: 'date_range', required: true },
  { key: 'payment_freq', label: 'Payment Frequency', type: 'dropdown', required: true, options: ['Monthly', 'Quarterly', 'Semi-Annually', 'Annually'] },
  { key: 'shariah_cert', label: 'Shariah Compliance Certification', type: 'file_upload', required: true },
  { key: 'redemption_mechanism', label: 'Redemption Mechanism', type: 'textarea', required: true },
];

export const mockBaiMuajjalSchema: FindingsSchema = [
  { key: 'asset_details', label: 'Asset Details', type: 'textarea', required: true },
  { key: 'sale_price', label: 'Sale Price', type: 'number', required: true },
  { key: 'payment_schedule', label: 'Payment Schedule', type: 'partner_list', required: true, placeholder: 'Installment table' },
  { key: 'ownership_transfer', label: 'Ownership Transfer Terms', type: 'textarea', required: true },
  { key: 'default_terms', label: 'Default Handling Terms', type: 'textarea', required: true },
];

// ─── Mock Assignments ─────────────────────────────────────

export const mockAssignments: Assignment[] = [
  {
    id: 'req-001',
    reference_number: 'MPVP-2026-00142',
    status: 'ASSIGNED',
    priority: 'URGENT',
    client_name: 'Al-Farooq Industries (Pvt.) Ltd.',
    contact_person: 'Mohammad Farhan Rashid',
    contact_phone: '+923211234567',
    site_address: 'Plot 215, SITE Area, Karachi, Sindh',
    branch_name: 'MCB Clifton Branch',
    contract_type: {
      id: 'ct-001',
      name: 'Istisna',
      code: 'IST',
      findings_schema: mockIstisnaSchema,
    },
    transaction_size: 'PKR 15,000,000',
    goods_description: 'Raw steel bars and construction fittings',
    consumption_cycle: '12 months',
    written_offer_date: '2026-02-20',
    declaration_date: '2026-02-22',
    assigned_by: 'Ops Center',
    assigned_at: '2026-02-25T09:00:00Z',
    due_date: '2026-02-28',
    days_remaining: 1,
    ops_notes: 'Client relocated warehouse to Plot 215 from Plot 180. Confirm new address on arrival. Security gate requires advance notice — call contact person 30 min before visit.',
    rejection_reason: null,
    job_response_deadline: '2026-02-28T12:00:00Z',
  },
  {
    id: 'req-002',
    reference_number: 'MPVP-2026-00156',
    status: 'ASSIGNED',
    priority: 'HIGH',
    client_name: 'Sindh Star Trading Co.',
    contact_person: 'Yusuf Mehmood',
    contact_phone: '+923331234567',
    site_address: 'Warehouse 12, I.I. Chundrigar Road, Karachi',
    branch_name: 'HBL Main Branch',
    contract_type: {
      id: 'ct-002',
      name: 'Salam',
      code: 'SAL',
      findings_schema: mockSalamSchema,
    },
    transaction_size: 'PKR 8,500,000',
    goods_description: 'Textile machinery components',
    consumption_cycle: '24 months',
    written_offer_date: '2026-02-22',
    declaration_date: '2026-02-24',
    assigned_by: 'Ops Center',
    assigned_at: '2026-02-26T10:00:00Z',
    due_date: '2026-03-05',
    days_remaining: 6,
    ops_notes: null,
    rejection_reason: null,
    job_response_deadline: '2026-03-01T18:00:00Z',
  },
  {
    id: 'req-003',
    reference_number: 'MPVP-2026-00171',
    status: 'IN_PROGRESS',
    priority: 'NORMAL',
    client_name: 'Pearl Properties (Pvt.) Ltd.',
    contact_person: 'Noor Fatima',
    contact_phone: '+923451234567',
    site_address: 'DHA Phase 6, Plot 44-C, Karachi',
    branch_name: 'BankIslami Shahrah-e-Faisal',
    contract_type: {
      id: 'ct-003',
      name: 'Murabaha',
      code: 'MUR',
      findings_schema: mockMurabahaSchema,
    },
    transaction_size: 'PKR 25,000,000',
    goods_description: 'Construction materials — cement, bricks, sanitary fittings',
    consumption_cycle: '6 months',
    written_offer_date: '2026-02-24',
    declaration_date: '2026-02-25',
    assigned_by: 'Ops Center',
    assigned_at: '2026-02-26T08:00:00Z',
    due_date: '2026-03-02',
    days_remaining: 3,
    ops_notes: null,
    rejection_reason: null,
    job_response_deadline: null,
  },
  {
    id: 'req-004',
    reference_number: 'MPVP-2026-00188',
    status: 'ASSIGNED',
    priority: 'LOW',
    client_name: 'Karachi Electronics Est.',
    contact_person: 'Ali Hassan',
    contact_phone: '+923001112233',
    site_address: 'Bolton Market, Shop 42, Karachi',
    branch_name: 'Meezan Bank Saddar',
    contract_type: {
      id: 'ct-004',
      name: 'Ijarah',
      code: 'IJA',
      findings_schema: mockIjarahSchema,
    },
    transaction_size: 'PKR 3,200,000',
    goods_description: 'Electronic components — capacitors, circuit boards',
    consumption_cycle: '6 months',
    written_offer_date: '2026-02-25',
    declaration_date: '2026-02-26',
    assigned_by: 'Ops Center',
    assigned_at: '2026-02-27T07:00:00Z',
    due_date: '2026-03-10',
    days_remaining: 11,
    ops_notes: null,
    rejection_reason: null,
    job_response_deadline: '2026-03-05T18:00:00Z',
  },
  {
    id: 'req-005',
    reference_number: 'MPVP-2026-00201',
    status: 'ASSIGNED',
    priority: 'NORMAL',
    client_name: 'Indus Motors (Pvt.) Ltd.',
    contact_person: 'Kamran Akmal',
    contact_phone: '+923005554433',
    site_address: 'Bin Qasim, Industrial Area, Karachi',
    branch_name: 'Standard Chartered Main',
    contract_type: {
      id: 'ct-008',
      name: 'Bai Muajjal',
      code: 'BAM',
      findings_schema: mockBaiMuajjalSchema,
    },
    transaction_size: 'PKR 55,000,000',
    goods_description: 'Automobile spare parts and assembly kits',
    consumption_cycle: '12 months',
    written_offer_date: '2026-02-26',
    declaration_date: '2026-02-27',
    assigned_by: 'Ops Center',
    assigned_at: '2026-02-28T09:00:00Z',
    due_date: '2026-03-15',
    days_remaining: 13,
    ops_notes: 'Verify ownership transfer documents carefully.',
    rejection_reason: null,
    job_response_deadline: '2026-03-05T12:00:00Z',
  },
];

// ─── Mock History Assignments ─────────────────────────────

export const mockHistoryAssignments: Assignment[] = [
  {
    id: 'hist-001',
    reference_number: 'MPVP-2026-00098',
    status: 'PUBLISHED',
    priority: 'NORMAL',
    client_name: 'Lahore Garments (Pvt.) Ltd.',
    contact_person: 'Amina Khalil',
    contact_phone: '+923009876543',
    site_address: 'Ferozepur Road, Industrial Estate, Lahore',
    branch_name: 'UBL Gulberg Branch',
    contract_type: {
      id: 'ct-005',
      name: 'Musharakah',
      code: 'MUS',
      findings_schema: mockMusharakahSchema,
    },
    transaction_size: 'PKR 12,000,000',
    goods_description: 'Garment raw materials — fabric rolls, zippers, buttons',
    consumption_cycle: '24 months',
    written_offer_date: '2026-01-10',
    declaration_date: '2026-01-12',
    assigned_by: 'Ops Center',
    assigned_at: '2026-01-14T09:00:00Z',
    due_date: '2026-01-24',
    days_remaining: 0,
    ops_notes: null,
    rejection_reason: null,
    job_response_deadline: null,
  },
  {
    id: 'hist-002',
    reference_number: 'MPVP-2026-00115',
    status: 'SUBMITTED',
    priority: 'NORMAL',
    client_name: 'Faisalabad Textiles BSC',
    contact_person: 'Sara Dosari',
    contact_phone: '+923335556666',
    site_address: 'Jhang Road, Faisalabad, Punjab',
    branch_name: 'Askari Bank Faisalabad',
    contract_type: {
      id: 'ct-006',
      name: 'Mudarabah',
      code: 'MUD',
      findings_schema: mockMudarabahSchema,
    },
    transaction_size: 'PKR 45,000,000',
    goods_description: 'Industrial looms and textile machinery',
    consumption_cycle: '48 months',
    written_offer_date: '2026-01-25',
    declaration_date: '2026-01-28',
    assigned_by: 'Ops Center',
    assigned_at: '2026-02-01T09:00:00Z',
    due_date: '2026-02-10',
    days_remaining: 0,
    ops_notes: null,
    rejection_reason: null,
    job_response_deadline: null,
  },
  {
    id: 'hist-003',
    reference_number: 'MPVP-2026-00135',
    status: 'RETURNED',
    priority: 'HIGH',
    client_name: 'Islamabad Construction Co.',
    contact_person: 'Omar Khalil',
    contact_phone: '+923129990000',
    site_address: 'Blue Area, Plot F-6/1, Islamabad',
    branch_name: 'Bank Alfalah F-6',
    contract_type: {
      id: 'ct-007',
      name: 'Sukuk',
      code: 'SUK',
      findings_schema: mockSukukSchema,
    },
    transaction_size: 'PKR 75,000,000',
    goods_description: 'Concrete, steel, marble flooring',
    consumption_cycle: '18 months',
    written_offer_date: '2026-02-05',
    declaration_date: '2026-02-07',
    assigned_by: 'Ops Center',
    assigned_at: '2026-02-10T09:00:00Z',
    due_date: '2026-02-18',
    days_remaining: 0,
    ops_notes: null,
    rejection_reason: 'Photos are blurry and do not clearly show the goods segregation area. Please retake photos with better lighting and include close-up shots of the material labels.',
    job_response_deadline: null,
  },
];

// ─── Mock Notifications ───────────────────────────────────

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-001',
    type: 'ASSIGNMENT_CREATED',
    title: 'New Assignment',
    body: 'MPVP-2026-00188 — Karachi Electronics Est. Due: 10 Mar',
    read: false,
    created_at: '2026-02-27T07:00:00Z',
    assignment_id: 'req-004',
    assignment_ref: 'MPVP-2026-00188',
  },
  {
    id: 'notif-002',
    type: 'SUBMISSION_RETURNED',
    title: 'Submission Returned',
    body: 'MPVP-2026-00135 — Islamabad Construction Co. requires revision',
    read: false,
    created_at: '2026-02-26T14:00:00Z',
    assignment_id: 'hist-003',
    assignment_ref: 'MPVP-2026-00135',
  },
  {
    id: 'notif-003',
    type: 'DEADLINE_WARNING',
    title: 'Deadline Approaching',
    body: 'MPVP-2026-00142 accept/reject deadline in 30 minutes',
    read: true,
    created_at: '2026-02-25T11:30:00Z',
    assignment_id: 'req-001',
    assignment_ref: 'MPVP-2026-00142',
  },
  {
    id: 'notif-004',
    type: 'ASSIGNMENT_CREATED',
    title: 'New Assignment',
    body: 'MPVP-2026-00156 — Sindh Star Trading Co. Due: 05 Mar',
    read: true,
    created_at: '2026-02-24T10:00:00Z',
    assignment_id: 'req-002',
    assignment_ref: 'MPVP-2026-00156',
  },
  {
    id: 'notif-005',
    type: 'DEADLINE_EXPIRED',
    title: 'Deadline Expired',
    body: 'MPVP-2026-00098 response window has closed',
    read: true,
    created_at: '2026-02-23T18:00:00Z',
    assignment_id: null,
    assignment_ref: 'MPVP-2026-00098',
  },
];
